// One-off image optimizer for the venue's real photography.
// Generates responsive WebP variants + a base64 LQIP blur map.
//   node scripts/optimize-images.mjs
import sharp from 'sharp'
import { readdir, writeFile, mkdir, readFile } from 'node:fs/promises'
import path from 'node:path'

// Venue photography organised by space (hall = La Salle, garden = Le Jardin).
// Sources live outside public/ (git-ignored) so raws aren't deployed; only the
// generated WebP under public/venue/hall/ ship. LQIP is merged below so
// regenerating a subset never drops entries whose source isn't checked in.
const SRC_DIR = path.resolve('source-photos/hall')
const OUT_DIR = path.resolve('public/venue/hall')
const WIDTHS = [480, 768, 1080, 1600, 1920]

const lqip = {}

const files = (await readdir(SRC_DIR)).filter((f) => /\.(jpe?g|png)$/i.test(f))

await mkdir(OUT_DIR, { recursive: true })

for (const file of files) {
  const name = file.replace(/\.(jpe?g|png)$/i, '')
  const input = path.join(SRC_DIR, file)
  const meta = await sharp(input).metadata()

  for (const w of WIDTHS) {
    if (meta.width && w > meta.width * 1.1) continue // don't upscale
    const out = path.join(OUT_DIR, `${name}-${w}.webp`)
    await sharp(input)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 72 })
      .toFile(out)
  }

  // Tiny blurred placeholder as an inlinable data URI
  const buf = await sharp(input)
    .resize({ width: 24 })
    .webp({ quality: 35 })
    .toBuffer()
  lqip[`/venue/hall/${file}`] = `data:image/webp;base64,${buf.toString('base64')}`
  console.log(`✓ ${file}`)
}

// Merge with existing placeholders so regenerating a subset keeps the rest
// (e.g. heroes whose source images aren't checked in).
const LQIP_PATH = path.resolve('src/data/lqip.ts')
let existing = {}
try {
  const prev = await readFile(LQIP_PATH, 'utf8')
  const m = prev.match(/LQIP: Record<string, string> = (\{[\s\S]*?\})\s*\n/)
  if (m) existing = JSON.parse(m[1])
} catch { /* first run — no file yet */ }
const merged = { ...existing, ...lqip }

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Maps each local venue asset to a tiny base64 blur placeholder (LQIP).
export const LQIP: Record<string, string> = ${JSON.stringify(merged, null, 2)}

/** Available responsive widths generated as WebP for /venue/* assets. */
export const VENUE_WIDTHS = ${JSON.stringify(WIDTHS)} as const
`
await writeFile(LQIP_PATH, ts)
console.log(`\nWrote src/data/lqip.ts: ${Object.keys(merged).length} placeholders (${Object.keys(lqip).length} new).`)
