// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Maps each local venue asset to a tiny base64 blur placeholder (LQIP).
export const LQIP: Record<string, string> = {
  "/venue/entrance.jpg": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoYACAAPwF2slOrJyQiqAgBYCAJYgDKAA64MdBgzbD91+PzO6RsAAD58f8nZHT73JfHwoBq5+/gJD+1ayjLc0Rs4GXJGHVO7bGwTp3if+rcluEzCPFyHHmA7+ccHBSVYy+LrZ7Ihl7skYWt9khPQ1xtgDirrYb6Gvi1y6g3+h352inMLgrKxn69zA69Geeb/mqsziAA",
  "/venue/exterior-night.jpg": "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAAAwBgCdASoYABoAPvVmqk6qpaQiMAwBUB6JbACsMoSBSdFtAm7BxC/XPdgcw0LSbWYFrTUzovzuFknAAP7ypDPQjuHVp7UA4QnmcQxh82VQUjOnRfnr3++8LmglZRPfeILeQ3QJCohghEJZFqbZpkazTEGwmu3i2eQJCJPB7rbn6atHce5Sd69xAiW/auOvt92GQA/TFJlTZgKreYcXv+bfj65ZOQHSCUMIMVOMKQE4vf6CbwgECvs30+lEJ6nianfk+/xVaPAe02Y6qHe2WnU42UG7xyPlcnu14OY7VAc+OCvG1Z6gX9y/3f7x3xX2NxnywlxFnUxjAcxIFGgbdaBvUzC2BmsNxwAAAA==",
  "/venue/hall-aisle.jpg": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoYAA0APwForE6rJiQiMAgBYCAJQBOkERhXDlh7ZV1PMlR2gAD2MFwipsKAQirCU3gOXGd1gdyw4hB878tP3OaTQTZgdDJ4rLxmzMtJzIy1ShSi9JeEf98npnIKejpKTF4MDmp4cnusyL5MoMbd0D8SkybuGwtK34iuOcgAAAA=",
  "/venue/hall-kosha.jpg": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAAAwBQCdASoYABMAPwF2slOrJySiqAgBYCAJYwCdAdwAXpPS074td7TPe9UxSi4sltBQsAD+3Xo5yIIDHGMKfC1xUwtWEwfr+Vtxn1knESI1zKq6OTaRruEo6yk5Jk24mLLHwkKt5YgFC7uHaOXAs33cOI8DfqYZxQGcPc3XfOzJFgiEO3cwrJRilPsJaAKIGi9RyIrdlbn1EO7hUw9vVIYTQR91UVqOnd5/9hkkFPLGQouzKCv9qUK+O3P+uYftCWuTKGYH5Sey46FVgQAAAA==",
  "/venue/table-setting.jpg": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAAAwBQCdASoYACAAPwF2slOrJySiqAgBYCAJYgCw8a9lAAczj+Hf1cXuLbGoUaLVA5DhsAD8glxif1J1rj1BRLNqvM5LwcXIpZugZDIUerv+FfYdIGgNwSaj7j7DWMArAmvY302sBHuMHaZk33HFxtkq2fC3ZzWK6JSUD3lx0ebqIcPx+zNcG9Xna7s9oOcGQFfnM71VwWFXQb05JtdcMoNmEkS/vb8IaCGkmEKjnqyFxgEeLIfyN53GMhlxwCvGCDP7NE1Mfh4qrWU6hJJba2YpAAA="
}

/** Available responsive widths generated as WebP for /venue/* assets. */
export const VENUE_WIDTHS = [480,768,1080,1600,1920] as const
